### ISSUE TITLE
<Integration TheFes/cheapest-energy-hours> Repository structure for v5.0.2 is not compliant

### ISSUE THREAD

**Issue by Neowam** [TheFes/cheapest-energy-hours#105]
I've encountered an issue with the TheFes/cheapest-energy-hours integration version 5.0.2. The repository structure does not seem to comply with HACS guidelines, making it challenging to add and update through the Home Assistant Community Store.

**Steps to Reproduce**
Attempt to add TheFes/cheapest-energy-hours via HACS.
Notice the integration is not recognized or added.

![image](https://github.com/TheFes/cheapest-energy-hours/assets/94406673/ea0af4fe-aecc-455f-b453-913165772ec9)

**Comment by Neowam** [comment]
Which requirement?

**Comment by TheFes** [comment]
The requirement to enable Experimental mode in HACS
https://github.com/TheFes/cheapest-energy-hours#how-to-install

> Custom templates are currently only available in HACS when you enable experimental features. Make sure to enable it in the HACS settings, which you can access from Settings > [Devices & Services](https://my.home-assistant.io/create-link/?redirect=integrations) > HACS When experimental features are enabled you click the button below to add it to your HACS installation,

**Comment by TheFes** [comment]
Also, this is a default HACS repository, you don't need to add it as a custom repository to HACS. It's already included in the lis (as soon as experimental features are enabled)

**Comment by TheFes** [comment]
Did you manage to get it running?

**Comment by Neowam** [comment]
Yes, now only finding out the setups my waterboiler charging. Thanks.

**Comment by TheFes** [comment]
Okay, I will close this issue then
