### ISSUE TITLE
Feature solar power

### ISSUE THREAD

**Issue by sebasjew** [TheFes/cheapest-energy-hours#134]
Is there also a way to do this via home assistent with solar power to turn on the nibe heatpump?

**Comment by TheFes** [comment]
Sorry, I don't fully understand what you'd like to achieve here

**Comment by sebasjew** [comment]
Af the moment when the solar panels are producing power I want the switch on the heat pump or the airco’s to heat the room. Hope this is more clear.

**Comment by TheFes** [comment]
That's indeed more clear, but it has nothing to do with this macro.
You can just create an automation which you trigger on the numeric state of your solar panel sensor, and then turn on the switch. If you need help on that you can ask on the Home Assistant community forum, or on the HA Discord server.

I close this issue now as it's unrelated to the macro
