### ISSUE TITLE
Template sensor does not work.

### ISSUE THREAD

**Issue by woopstar** [TheFes/cheapest-energy-hours#139]
I added the dishwasher example to my template sensor, but somehow, the sensor states it's Unknown. If I paste it into the template editor, the sensor works:

![image](https://github.com/TheFes/cheapest-energy-hours/assets/2997782/63ee9740-829e-4eb7-80fc-10428a1aa6b4)

Is there something to consider when you have template sensors in files included in your HA configuration?

**Comment by TheFes** [comment]
It will be `unknown` until it triggers for the first time

**Comment by woopstar** [comment]
Confirmed
