### ISSUE TITLE
No longer compatible?

### ISSUE THREAD

**Issue by AlexJacu** [TheFes/cheapest-energy-hours#142]
when add to HA via HACS, i get the following error: "<Integration TheFes/cheapest-energy-hours> Repository structure for v5.5.1 is not compliant"

Core 2024.6.2
Supervisor 2024.06.0
Operating System 12.3
Frontend 20240610.0

**Comment by TheFes** [comment]
You need to enable experimental features in HACS first to be able to install custom templates

**Comment by TheFes** [comment]
Closing this issue. As I received no further reply I assume it's resolved by enabling experimental features.
