### ISSUE TITLE
None rendered invalid date

### ISSUE THREAD

**Issue by woopstar** [TheFes/cheapest-energy-hours#153]
Created a template sensor and got the following warning while the sensor was unknown.

Just went into the Helper section and created a template sensor with the following:

```
{%- from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
{{ cheapest_energy_hours(sensor='sensor.energi_data_service', hours=1, look_ahead=true, include_tomorrow=false) }}
```

The following error occurs:

```
2024-08-12 20:52:08.233 WARNING (MainThread) [homeassistant.components.sensor.helpers] None rendered invalid date 2024-08-12T13:00:00+02:00
```

**Comment by woopstar** [comment]
I did set the device class to date and not timestamp. Maybe that is the issue

**Comment by TheFes** [comment]
Yes, that will cause this error.
`device_class: timestamp` is the device class to use for a isoformat datetime string.
`devcie_class: date` only works on the a isoformat date string like `2024-08-13`
