### ISSUE TITLE
[REQUEST] Add Central Hudson Gas & Electric

### ISSUE THREAD

**Issue by wormuths** [TheFes/cheapest-energy-hours#155]
Can you please see if there is a way to add Central Hudson in New York, that would be awesome.

https://www.cenhud.com/en/account-resources/rates/gas--electric-supply-prices/

That's all I could find.  I don't know if you have any other ways to scrape their data, or if it's even possible with this provider.  I'd appreciate if you could check it out.

Thanks!

**Comment by TheFes** [comment]
Creating integrations to retreive the data from your provider is not the intentation of this repository or macro. It's to work with the data after you have it in Home Assistant. 
I can't help you with your request, you can maybe ask on the community forum, or on Discord for help with scraping this data.
