### ISSUE TITLE
Adding through HACS fails - repo is not compliant?

### ISSUE THREAD

**Issue by emar-dw** [TheFes/cheapest-energy-hours#157]
I'm getting an error in HACS when trying to add this repo in the 'custom repo' list:
<Integration TheFes/cheapest-energy-hours> Repository structure for v5.5.2 is not compliant

Could it be that the requirements changed?

**Comment by TheFes** [comment]
You probably didn't update to HACS 2.0 yet and didn't enable experimental features.
So that means there is no support for custom templates.

So either update to HACS 2.0, or enable experimental features.

**Comment by emar-dw** [comment]
Yes, that was it, thanks. Didn't realise HACS 2.0 was needed.
