### ISSUE TITLE
expensivest Timeframe error

### ISSUE THREAD

**Issue by rschoell** [TheFes/cheapest-energy-hours#163]
Hi TheFes,

I've started using your code to charge and discharge a battery based on Tibber. All working perfect the last few days. 
Today am not getting the most expensive hours. 
The sensor shows this error:

1 error: 71 datapoints (5.916666666666667 hours) in selection, where 108 (9.0 hours) are expected

the code used to create this is as follows:

{% set sensor = 'sensor.tibber_prices_2' %}
{% set hours = states('sensor.b2240_entladezeit_errechnet') | float %}
{% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
{{ cheapest_energy_hours(sensor=sensor, hours=hours, include_tomorrow=true, split=true, look_ahead=true, lowest=false, price_tolerance=0.11, mode='is_now') }}

The discharge hours to be calculated are as shown in the error around 9 hours. 
How can I fix this please?

many thanks
Ralph

**Comment by TheFes** [comment]
Are you using the core Tibber integration, or the custom component? 

Based on the time you posted this, it was around 18:00. So it looks like your price sensor didn't update with the prices of tomorrow, meaning there was roughly 6 hours of price information available. 
As at least 9 hours of data was required, this error was shown.

**Comment by rschoell** [comment]
Using the core tibber integration. Prices were in the sensor, but this somehow lacked. 10 Minutes later, I realized it being ok again, but it toggled between 44 datapoints and 108. Just wanted to let you know there might appear some issues sometimes. Guess we can close it for now.
