### ISSUE TITLE
not the cheapest slot?

### ISSUE THREAD

**Issue by TylonHH** [TheFes/cheapest-energy-hours#168]
Hello there,

I managed somehow to get this run. I have this sensor set up:
```
{%- set sensor = 'sensor.tibber_prices_2' -%}
          {% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
          {{ cheapest_energy_hours(sensor=sensor, hours=3, start='00:00', end='00:00', include_tomorrow=true) }}
```

![grafik](https://github.com/user-attachments/assets/42704856-a828-482c-97aa-72b57b47c707)

The result: `2024-11-03T10:00:00+00:00` so today at 10:00 oClock starts the cheapest 3hrs.

1. I wonder why +00:00 as I'm in Germany. I would expect +01:00

2. maybe related to the timezone, but I expected the cheapest hours at 11:00 see graph
![image](https://github.com/user-attachments/assets/25144541-4dbc-4452-90d8-9a9e0b94e4e4)

**Comment by TheFes** [comment]
10:00:00+00:00 is the same as 11:00:00+01:00

And I guess HA uses UTC for sensors using device_class: timestamp, what result do you get when you use the template in devtools > template?

**Comment by TheFes** [comment]
Tested it myself, and it indeed converts the state to UTC, which it no issue for the usage. 
If you'd use it in a time trigger, it will trigger at 11:00 local time

**Comment by TylonHH** [comment]
I'll keep an eye on it.
