### ISSUE TITLE
New in this

### ISSUE THREAD

**Issue by thomasssso** [TheFes/cheapest-energy-hours#169]
Not really a issue, just spend a lot of time finding out how to set it up. Perhaps a good instruction would help. Looks like a cool integration. However I cannot get past stage 1, installing the sensor data. Really stuck here how to set this up. Running the following template

{{ state_attr('sensor.current_electricity_price_all_in', 'prices') }}

gives me really nice data. (see below) But have no idea how to setup the sensor in a way I can start using the app. I know how to edit the configuration.yaml file. But unclear how to then use the data. Anybody knows perhaps a good tutorial or video?

[{'from': datetime.datetime(2024, 11, 3, 23, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 0, 0, tzinfo=tzutc()), 'price': 0.2612}, {'from': datetime.datetime(2024, 11, 4, 0, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 1, 0, tzinfo=tzutc()), 'price': 0.2586}, {'from': datetime.datetime(2024, 11, 4, 1, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 2, 0, tzinfo=tzutc()), 'price': 0.2588}, {'from': datetime.datetime(2024, 11, 4, 2, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 3, 0, tzinfo=tzutc()), 'price': 0.2577}, {'from': datetime.datetime(2024, 11, 4, 3, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 4, 0, tzinfo=tzutc()), 'price': 0.2589}, {'from': datetime.datetime(2024, 11, 4, 4, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 5, 0, tzinfo=tzutc()), 'price': 0.2677}, {'from': datetime.datetime(2024, 11, 4, 5, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 6, 0, tzinfo=tzutc()), 'price': 0.2977}, {'from': datetime.datetime(2024, 11, 4, 6, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 7, 0, tzinfo=tzutc()), 'price': 0.3192}, {'from': datetime.datetime(2024, 11, 4, 7, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 8, 0, tzinfo=tzutc()), 'price': 0.3157}, {'from': datetime.datetime(2024, 11, 4, 8, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 9, 0, tzinfo=tzutc()), 'price': 0.2952}, {'from': datetime.datetime(2024, 11, 4, 9, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 10, 0, tzinfo=tzutc()), 'price': 0.2703}, {'from': datetime.datetime(2024, 11, 4, 10, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 11, 0, tzinfo=tzutc()), 'price': 0.2517}, {'from': datetime.datetime(2024, 11, 4, 11, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 12, 0, tzinfo=tzutc()), 'price': 0.2503}, {'from': datetime.datetime(2024, 11, 4, 12, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 13, 0, tzinfo=tzutc()), 'price': 0.2517}, {'from': datetime.datetime(2024, 11, 4, 13, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 14, 0, tzinfo=tzutc()), 'price': 0.2646}, {'from': datetime.datetime(2024, 11, 4, 14, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 15, 0, tzinfo=tzutc()), 'price': 0.3018}, {'from': datetime.datetime(2024, 11, 4, 15, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 16, 0, tzinfo=tzutc()), 'price': 0.3603}, {'from': datetime.datetime(2024, 11, 4, 16, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 17, 0, tzinfo=tzutc()), 'price': 0.4762}, {'from': datetime.datetime(2024, 11, 4, 17, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 18, 0, tzinfo=tzutc()), 'price': 0.4299}, {'from': datetime.datetime(2024, 11, 4, 18, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 19, 0, tzinfo=tzutc()), 'price': 0.3449}, {'from': datetime.datetime(2024, 11, 4, 19, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 20, 0, tzinfo=tzutc()), 'price': 0.2986}, {'from': datetime.datetime(2024, 11, 4, 20, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 21, 0, tzinfo=tzutc()), 'price': 0.283}, {'from': datetime.datetime(2024, 11, 4, 21, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 22, 0, tzinfo=tzutc()), 'price': 0.2768}, {'from': datetime.datetime(2024, 11, 4, 22, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 4, 23, 0, tzinfo=tzutc()), 'price': 0.262}, {'from': datetime.datetime(2024, 11, 4, 23, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 0, 0, tzinfo=tzutc()), 'price': 0.251}, {'from': datetime.datetime(2024, 11, 5, 0, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 1, 0, tzinfo=tzutc()), 'price': 0.2635}, {'from': datetime.datetime(2024, 11, 5, 1, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 2, 0, tzinfo=tzutc()), 'price': 0.2595}, {'from': datetime.datetime(2024, 11, 5, 2, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 3, 0, tzinfo=tzutc()), 'price': 0.2603}, {'from': datetime.datetime(2024, 11, 5, 3, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 4, 0, tzinfo=tzutc()), 'price': 0.2635}, {'from': datetime.datetime(2024, 11, 5, 4, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 5, 0, tzinfo=tzutc()), 'price': 0.2661}, {'from': datetime.datetime(2024, 11, 5, 5, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 6, 0, tzinfo=tzutc()), 'price': 0.2781}, {'from': datetime.datetime(2024, 11, 5, 6, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 7, 0, tzinfo=tzutc()), 'price': 0.3144}, {'from': datetime.datetime(2024, 11, 5, 7, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 8, 0, tzinfo=tzutc()), 'price': 0.3146}, {'from': datetime.datetime(2024, 11, 5, 8, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 9, 0, tzinfo=tzutc()), 'price': 0.2929}, {'from': datetime.datetime(2024, 11, 5, 9, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 10, 0, tzinfo=tzutc()), 'price': 0.2779}, {'from': datetime.datetime(2024, 11, 5, 10, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 11, 0, tzinfo=tzutc()), 'price': 0.2651}, {'from': datetime.datetime(2024, 11, 5, 11, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 12, 0, tzinfo=tzutc()), 'price': 0.2646}, {'from': datetime.datetime(2024, 11, 5, 12, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 13, 0, tzinfo=tzutc()), 'price': 0.2699}, {'from': datetime.datetime(2024, 11, 5, 13, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 14, 0, tzinfo=tzutc()), 'price': 0.2805}, {'from': datetime.datetime(2024, 11, 5, 14, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 15, 0, tzinfo=tzutc()), 'price': 0.3311}, {'from': datetime.datetime(2024, 11, 5, 15, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 16, 0, tzinfo=tzutc()), 'price': 0.5167}, {'from': datetime.datetime(2024, 11, 5, 16, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 17, 0, tzinfo=tzutc()), 'price': 0.7221}, {'from': datetime.datetime(2024, 11, 5, 17, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 18, 0, tzinfo=tzutc()), 'price': 0.6713}, {'from': datetime.datetime(2024, 11, 5, 18, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 19, 0, tzinfo=tzutc()), 'price': 0.5374}, {'from': datetime.datetime(2024, 11, 5, 19, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 20, 0, tzinfo=tzutc()), 'price': 0.3551}, {'from': datetime.datetime(2024, 11, 5, 20, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 21, 0, tzinfo=tzutc()), 'price': 0.307}, {'from': datetime.datetime(2024, 11, 5, 21, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 22, 0, tzinfo=tzutc()), 'price': 0.2923}, {'from': datetime.datetime(2024, 11, 5, 22, 0, tzinfo=tzutc()), 'till': datetime.datetime(2024, 11, 5, 23, 0, tzinfo=tzutc()), 'price': 0.2829}]

**Comment by TheFes** [comment]
This data looks like data which can be used by the macro. But without any explanation of what you want to achieve, I can't really help you

**Comment by TheFes** [comment]
As I received no further explanation, I will close this issue now.
