### ISSUE TITLE
Developer tools > Services no longer exists

### ISSUE THREAD

**Issue by thomasssso** [TheFes/cheapest-energy-hours#173]
Trying to get the template to work. A small suggestion in the manual (perhaps more will follow) 

In the documentation for the 'template sensor configuration' you refer to the developertools > services. This does no longer exist and has been replaces by developertools > actions.

[background](https://www.home-assistant.io/blog/2024/08/07/release-20248/#goodbye-service-calls-hello-actions-)

Could you please update this in the manual?

**Comment by TheFes** [comment]
Ah, sure, I will change that in the documentation

**Comment by thomasssso** [comment]
Thanks for the quick reply. I am new to this and trying to get the code working. But this is quite a challenge. Seems that some updates have outdated your manual. Just spend some hours getting the energy_Zero template to work. For future users pleas add that they can add the code to the configuration.yaml file (this is the easiest way) and the code for energy zero should look like this:

`# Example configuration entry
template:
  - trigger:
      - trigger: time_pattern
        hours: "/1" #update every hour
      - trigger: homeassistant
        event: start #update during start of Homeassistant
    action:
      - action: energyzero.get_energy_prices
        data:
          incl_vat: true
          config_entry: 2cff44427073c9dbd7fe6b12df78d9ce # replace with the config entry for your entity
          start: "{{ today_at() - timedelta(days=1) }}"
          end: "{{ today_at() + timedelta(days=2) }}"
        response_variable: prices
    sensor:
      - name: "energieprijzen_zero"
        state: "{{ prices.prices }}"
        attributes:
          prices: "{{prices.prices}}"`

hope this will help future users. I still don't have the system working perhaps more updates will follow and we can improve the documentation together.

**Comment by TheFes** [comment]
Sure, thanks for your improvements.
Also feel free to add them as PR directly.

**Comment by TheFes** [comment]
I've made some changes. I'm not sure what you changed in the YAML for the template sensor, besides the comments explaining what the triggers do. I've added that as an alias to the trigger.

**Comment by TheFes** [comment]
As I received no further comments, I will close this issue now.
