### ISSUE TITLE
can I get the cheapest hour today AND tomorrow within a timespan (08:00-20:)00?

### ISSUE THREAD

**Issue by TylonHH** [TheFes/cheapest-energy-hours#174]
So this is my sensor so far. I use the integrated tibber source sensor. after 13 oclock I have the data from tomorrow.

```
{%- set sensor = 'sensor.tibber_forecast' -%}
          {% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
          {{ cheapest_energy_hours(sensor=sensor, hours=3, start='06:00', end='20:00', include_tomorrow=true, look_ahead=true) }}
```
I got  2024-11-15T02:00:00+01:00 

Is it easy possible, or do I have to use two sensors and take care when thy will be set?
the best would be if I calculate the timestamp once a day at 13oclock, wouldnt?

**Comment by TheFes** [comment]
sorry, I don't really understand which time period you want to use now. What you have now will give you start time of the cheapest consecutive 3 hour period starting now (unless it is before 6:00 in the morning, then it will start at 6:00) and ending tomorrow at 20:00, unless that data is not available yet, then it will be ending at midnight.

If you want to ensure it uses tomorrows data as well, you need to make sure the template is only rendered when tomorrows data is available, so if that is after 13:00 you can make a trigger based template sensor which does that for you.

**Comment by TylonHH** [comment]
My goal is to identify the cheapest 3-hour window, adapting based on the time of day, but only between 6:00 and 20:00.
	1.	Morning (e.g., 5:00 AM): Evaluate today’s data only, finding the cheapest 3-hour period between 06:00 and 20:00.
	2.	Afternoon (e.g., 15:00): Evaluate today’s remaining hours **AND** tomorrow’s data (if available after 13:00) to find the cheapest 3-hour period between 06:00 and 20:00 rest of today AND between 6-20 tomorrow.

I aim to ensure accurate data consideration based on availability, potentially using different sensors or templates for morning and afternoon. Let me know if this aligns with what you’re suggesting.

**Comment by TheFes** [comment]
starting at what time do you want to include the part after 20:00 of the current day?

**Comment by TylonHH** [comment]
I don’t want to include any period after 20:00 of the current day. Instead, from that point onwards, the slot for the next day should be determined, as the prices are already available. I do not expect a time slot at 2 AM or during the night.

**Comment by TheFes** [comment]
so, from what point onward do you want to use the data from tomorrow? Is that only after 20:00, or earlier on the day already?

**Comment by TheFes** [comment]
ah wait, I get it now. You can't do that in one template
You need to do today, and tomorrow, and compare them.

So if the data from tomorrow is available, what do you want to see? The cheapest one between today and tomorrow? The earliest one? Both?

**Comment by TheFes** [comment]
I think this is what you want

```jinja2
{% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
{% set sensor = 'sensor.nordpool_kwh_nl_eur_3_10_021' %}

{% set today = cheapest_energy_hours(sensor, start='06:00', end='20:00', look_ahead=true, mode='all', value_on_error=[]) | from_json %}
{% set tomorrow = cheapest_energy_hours(sensor, start='06:00', end='20:00', look_ahead=true, mode='all', include_today=false, include_tomorrow=true, value_on_error={}) | from_json %}

{{ [today, tomorrow] | select() | sort(attribute='avarage') | map(attribute='start') | first }}
```

**Comment by TylonHH** [comment]
Awesome... seems to work.
I will have an eye on it.

Really great work.

Bonus: I saw in the output docs there is an 'average' for the average price of the slot.
Do I need a second sensor to get this?

**Comment by TylonHH** [comment]
So, I have now the prices for tomorrow. In the basic sensor tibber_forecast I also see prices from yesterday.
I guess because of
```
    action:
      - service: tibber.get_prices
        data:
          start: "{{ (today_at() - timedelta(days=1)).strftime('%Y-%m-%d %H:%M:%S') }}"
          end: "{{ (today_at() + timedelta(days=2)).strftime('%Y-%m-%d %H:%M:%S') }}"
```
So I changed to start= today + 0

But event then with your new suggestioned code I stil got timestamp from today = now, because arent getting shipper until 20:00, but tomorrow. But tomorrow isnt get catched!?

**Comment by TheFes** [comment]
I would recommend to include yesterdays data as well in the template sensor, it can be very useful if you want to use a time period which spans the night.

I must say I'm a bit confused with the rest of your post, not sure what you are trying to say here.

If the there is a cheaper option today, and that cheapest option the current time, it will show that.
If you test now, it should give a time tomorrow.

**Comment by TheFes** [comment]
Is your issue solved now?
