### ISSUE TITLE
Charge car even if number of hours are insufficient to fully charge to target

### ISSUE THREAD

**Issue by siljelb** [TheFes/cheapest-energy-hours#176]
Thank you so much for this excellent template!

I'm using the "Charge the car using the lowest rates" example, which is generally working really well. The only exception is when the time until the "input_datetime.leave home again" is smaller than the remaining charge time. My expectation in this case would be that the car would charge the entire time until the set time to leave home no matter the prices, but it looks like it's throwing an error like "7.0 hours between start and end, where 9.0 hours are required" and telling the automation to turn off the charging instead. Is there a way to handle this situation more gracefully?

**Comment by TheFes** [comment]
you can use the `value_on_default` parameter to return the current time, or maybe `true`  (depending on your other parameters) to have it return a value you can work with.

**Comment by siljelb** [comment]
Thank you, I think it does! I hadn't found that particular error message.

Changing my binary sensor to something like this seems to work (also added logic to handle when I forget to change the time when I need the car to be charged:
```yaml
template:
  - binary_sensor:
      - unique_id: 911f0a21-48de-438f-90a2-4b46401268b3
        name: Charge Car Cheap
        state: >-
          {% set sensor = 'sensor.nordpool' %}
          {% set hours = states('sensor.ioniq_5_estimated_portable_charge_duration') | float / 60 | round(0) %}
          {% set end = states('input_datetime.tidspunkt_dra_hjemmefra') %}
          {% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}

          {% macro evaluate(sensor, hours, end) %}
            {% set result = cheapest_energy_hours(sensor=sensor, hours=hours, start=now(), end=end, mode='is_now') %}
            {% if result | regex_match('^[\d]+ error[s]?: [\d.]+ hours between start and end, where [\d.]+ hours are required$') %}
              true
            {% elif result | regex_match('^[\d]+ error[s]?: Selected start parameter is after the end parameter$') %}
              {% set end = (now() + timedelta(hours=12)).isoformat() %}
              {{ evaluate(sensor, hours, end) }}
            {% else %}
              {{ result }}
            {% endif %}
          {% endmacro %}

          {{ evaluate(sensor, hours, end) }}
        availability: >-
          {{
            is_state('device_tracker.ioniq_5_location', 'home')
            and is_state('binary_sensor.ioniq_5_ev_battery_plug', 'on')
            and states('sensor.ioniq_5_estimated_portable_charge_duration') | is_number
          }}
```
