### ISSUE TITLE
No valid data in selected sensor

### ISSUE THREAD

**Issue by Swerfer** [TheFes/cheapest-energy-hours#34]
I tried this code in the template editor:

`{% from "cheapest_energy_hours.jinja" import cheapest_energy_hours %}
{{ cheapest_energy_hours("sensor.nordpool_kwh_nl_eur", hours=3) }}`

I get the error 'No valid data in the selected sensor'.

This is part of my Nordpool sensor:

Raw today
- start: '2023-08-05T00:00:00+02:00'
end: '2023-08-05T01:00:00+02:00'
value: 12.288
- start: '2023-08-05T01:00:00+02:00'
end: '2023-08-05T02:00:00+02:00'
value: 11.483
- start: '2023-08-05T02:00:00+02:00'
end: '2023-08-05T03:00:00+02:00'
value: 11.202
- start: '2023-08-05T03:00:00+02:00'
end: '2023-08-05T04:00:00+02:00'
value: 10.926

Price in cents
true

**Comment by TheFes** [comment]
Are you sure you provided the correct entity id?

**Comment by Swerfer** [comment]
Hmm... You're right. I had multiple Nordpool sensors and used the wrong one.

Thanks for the great macro!
