### ISSUE TITLE
Not getting the cheapest hour

### ISSUE THREAD

**Issue by tonnyongit** [TheFes/cheapest-energy-hours#35]
First of all i would like to say this is a great macro, this is exactly what i was looking for. Only I ran into a problem and this can be completely my fault.

I have entered the following in the dev/template:
```
{% from "cheapest_energy_hours.jinja" import cheapest_energy_hours %}
{{ cheapest_energy_hours("sensor.nordpool_kwh_nl_eur", hours=3, time_format="time24", look_ahead=true) }}
```

This is the raw data from the nordpool integration:
```
- start: '2023-08-21T11:00:00+02:00'
  end: '2023-08-21T12:00:00+02:00'
  value: 0.089
- start: '2023-08-21T12:00:00+02:00'
  end: '2023-08-21T13:00:00+02:00'
  value: 0.075
- start: '2023-08-21T13:00:00+02:00'
  end: '2023-08-21T14:00:00+02:00'
  value: 0.065
- start: '2023-08-21T14:00:00+02:00'
  end: '2023-08-21T15:00:00+02:00'
  value: 0.078
- start: '2023-08-21T15:00:00+02:00'
  end: '2023-08-21T16:00:00+02:00'
  value: 0.087
```

But when I ran that this morning at 1100am it came back a time of 1200 where I expected 1300 hours, then at 1200 it stayed 1200 and at 1300 it stayed 1300. 

Is there something I'm doing wrong or is this a problem?

**Comment by tonnyongit** [comment]
This is what I actually mean, here you can see that I have selected 3 hours and it comes up with a time tomorrow (I know I also included tomorrow with include). What I would expect is that he would return me the cheapest time in the next 3 hours.

![image](https://github.com/TheFes/cheapest-energy-hours/assets/109175709/c3d246a5-6096-4738-bc82-0e3c919f4d20)

I want to use this in an automation or script, when I take a shower it switches off the water heater and I would like it to switch on at the cheapest time, for example, in the next 3 hours. In the end I would also like to switch my battery pack so that it switches from the grid to my battery pack in the most expensive hours and if it is not cheap in the next 5 hours, it will heat the boiler via my battery pack and then charge my pack again at the cheapest times. But first I want to get this working

**Comment by tonnyongit** [comment]
Yes the mistake is on my end, I completely misunderstood the description. My knowledge of jinja is certainly not what it should be, but I'm working on it. If I use the function "start" and "end" I get the desired result. How to make this dynamic (start and end ) I'm not quite sure yet but this is not the right place for it. I'm sorry for my post here

**Comment by TheFes** [comment]
Happy to help you with the dynamic start and end as well
Let's say it's 12:15 now and you want it to start at 12:00 and end at 16:00, you can use `end=(now() +  timedelta(hours=4)).strftime('%H:00')`
For the start you can use `start=now().strftime('%H:00')` or just `look_ahead=true`

**Comment by tonnyongit** [comment]
@TheFes 
Has anyone told you today that you're doing a good job? ..

Well then you will get it from me now haha. 

Thank you this was very helpful, I was already breaking my head how I could get this done. I looked into your code and saw that you used it there too just in a slightly different way, that's why I was already reading [here](https://docs.python.org/3.8/library/datetime.html#timedelta-objects) but couldn't get it done.

This is what I have come up with now:
`{{ cheapest_energy_hours("sensor.nordpool_kwh_nl_eur", hours=1, look_ahead=true, end=(now() +  timedelta(hours=4)).strftime('%H:00'), include_tomorrow=true) }}`

Thanks again and also for your contribution this is a very handy tool

**Comment by tonnyongit** [comment]
@TheFes 

I have another question about the dynamic end time. I noticed last night after taking a shower that it had selected a time for the next day. The time window was correct, but only the day was wrong. I also notice that if I don't include the next day and the time window extends over the day, I don't receive any data (no data is returned at 2100 with a time window of 4 hours). Do you also have an idea about how to solve this, so that it truly only looks for the cheapest moment in the next 4 hours or so?

**Comment by TheFes** [comment]
You should only use `include_tomorrow=true` if the period ends tomorrow
This will probably work
```jinja2
{% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
{% set end = (now() +  timedelta(hours=4)).strftime('%H:00') %}
{% set tomorrow = iif(now() > today_at(end)) %}
{{ cheapest_energy_hours("sensor.nordpool_kwh_nl_eur_3_10_021", hours=1, look_ahead=true, end=end, include_tomorrow=tomorrow) }}
```

**Comment by tonnyongit** [comment]
I appreciate your response, and thank you for solving the issue within the "control structure." It hadn't occurred to me to approach it that way; I was mainly focused on the "expressions," but unfortunately, I couldn't make progress in that direction. I did manage to achieve a functional solution, but it didn't quite align with your macro.

Honestly, I initially hesitated to ask for help, as I usually like to figure things out on my own. However, I've come to realize that a little assistance can sometimes go a long way! Learning and implementing this within Home Assistant has been quite an enjoyable experience for me.

Thanks again for your guidance and prompt response!
