### ISSUE TITLE
unable to ad it on hacs

### ISSUE THREAD

**Issue by kurtdefeyter** [TheFes/cheapest-energy-hours#50]
when i click the add button the result is 
![afbeelding](https://github.com/TheFes/cheapest-energy-hours/assets/125728797/d5635564-a503-4871-abcf-b5dc95fbb28e)

**Comment by TheFes** [comment]
Did you enable experimental mode in HACS first?

**Comment by TheFes** [comment]
From: https://github.com/TheFes/cheapest-energy-hours#how-to-install
>  Custom templates are currently only available in HACS when you enable experimental features. Make sure to enable it in the HACS settings, which you can access from Settings > [Devices & Services](https://my.home-assistant.io/create-link/?redirect=integrations) >HACS

**Comment by kurtdefeyter** [comment]
hi Martijn , thank you for your quick response , i should have had a better look towards your documentation , its working like a charm now , please keep up the good work , and thanks

**Comment by TheFes** [comment]
Thanks for the confirmation!
