### ISSUE TITLE
Now again :-)

### ISSUE THREAD

**Issue by rhgiter** [TheFes/cheapest-energy-hours#74]
Sorry, but it dont seems to work 

my pc time is after 21.00 

the template shows 21:00

{{ cheapest_energy_hours("sensor.energi_data_service", hours=1, time_format="%H:%M:%S", start="21:00", end="0:00", include_tomorrow=true, look_ahead_minutes=0) }}  (same with =60)

I think the template should set the time to the next 15 minutes 21:15 21:30 21:45 ....  

![image](https://github.com/TheFes/cheapest-energy-hours/assets/61065752/654512e7-d24f-4eaa-b749-054a247326b1)

**Comment by TheFes** [comment]
Should be fixed in `v4.2.3. now

**Comment by rhgiter** [comment]
is possibe to make it so it will trigger every 15 minutes ?
instead og every hour. 

(ex. cheapest hour is 11.00 - the time now is 11.03. - but it change it to 12.00) it could be nice if it would be 11.15.)

{% from "cheapest_energy_hours.jinja" import cheapest_energy_hours %}
{{ cheapest_energy_hours("sensor.energi_data_service", hours=4, time_format="%H:%M:%S", start="6:00", end="17:00", look_ahead=true, look_ahead_minutes=5) }}

**Comment by TheFes** [comment]
Yes, I think I already figured out a way to handle this kind of situations. Will try to do an update today or tomorrow

**Comment by rhgiter** [comment]
Thanks. I have made "is_now", then it should change to TRUE, and my automation should trigger if the same hour is the cheapest.

{{ cheapest_energy_hours("sensor.energi_data_service", hours=1, time_format="%H:%M:%S", start="21:00", end="06:00", include_tomorrow=true, look_ahead=true, look_ahead_minutes=5, mode="is_now") }}


Thanks again for this integration. :-)
