### ISSUE TITLE
include_tomorrow discards end time

### ISSUE THREAD

**Issue by Grib1** [TheFes/cheapest-energy-hours#85]
When there's no data for tomorrow yet, I seem to face the end parameter to be discarded.

`{% print cheapest_energy_hours('sensor.energi_data_service', end="16:00", hours=2, look_ahead=true, include_tomorrow=false) %}`

Gives the expected output: 2023-11-13T14:00:00+01:00
If I change include_tomorrow to true, I get: 2023-11-13T22:00:00+01:00

**Comment by TheFes** [comment]
if `include_tomorrow` is set to `false`, `end='16:00'` will be 16:00 today.
If `include_tomorrow` is set to `true` it will be 16:00 tomorrow

When there is no data for tomorrow yet, `include_tomorrow=true, end='16:00'`  will in practice be the end of the current day.

**Comment by Grib1** [comment]
Got it, thanks.
I'll to my template add a line to switch `include_tomorrow` based on whether there's data for tomorrow or not.
